src/Extends/Badminton/Badminton.Web.Plugin/Areas/Badminton/Controllers/BrandController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Badminton.Consumableses;
using Badminton.Dao;
using Qi.Web.Mvc;

namespace Badminton.Web.Plugin.Areas.Badminton.Controllers
{
    [ Session]
    public class BrandController : Controller
    {
        private readonly IBadmintonDaoFactory _daoFactory;

        public BrandController(IBadmintonDaoFactory daoFactory)
        {
            _daoFactory = daoFactory;
        }

        //
        // GET: /Badminton/Brand/

        public ActionResult Index()
        {
            IList<Brand> result = _daoFactory.BrandDao().GetAll();
            return View(result);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                throw new HttpException(404, "NotFind");
            Brand brand = _daoFactory.BrandDao().Get(id.Value);
            return View(brand);
        }

        [HttpPost]
        public ActionResult Edit(Brand brand)
        {
            if (ModelState.IsValid)
            {
                _daoFactory.BrandDao().SaveOrUpdate(brand);
                return Redirect("index");
            }
            return View(brand);
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Brand brand)
        {
            if (ModelState.IsValid)
            {
                _daoFactory.BrandDao().SaveOrUpdate(brand);
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        [HttpPost]
        public ActionResult Save(Brand brand)
        {
            if (ModelState.IsValid)
            {
                _daoFactory.BrandDao().SaveOrUpdate(brand);
            }
            else
            {
                return Json(new
                    {
                        success = false,
                        message = ModelState.Values.First()
                    });
            }
            return Json(new
                {
                    success = true,
                    brand
                });
        }
    }
}

src/Extends/Badminton/Badminton.Web.Plugin/Areas/Badminton/Controllers/GymnasiumController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Badminton.Dao;
using Badminton.Web.Plugin.Areas.Badminton.Models;
using Ornament.Web;
using Ornament.Web.UI.Paginations;
using Qi.Web.Mvc;

namespace Badminton.Web.Plugin.Areas.Badminton.Controllers
{
    [Session]
    public class GymnasiumController : Controller
    {
        private readonly IBadmintonDaoFactory _daoFactory;

        public GymnasiumController(IBadmintonDaoFactory daoFactory)
        {
            _daoFactory = daoFactory;
        }

        public ActionResult Index(Pagination pagination)
        {
            if (pagination == null && pagination.PageSize != 1)
                pagination = new Pagination(1, 0);
            int total;
            IList<Gymnasium> result = _daoFactory.GymasiumDao()
                                                 .GetGymnasiums(pagination.PageSize, pagination.CurrentPage, out total);
            pagination.TotalRows = total;
            ViewData["nav"] = pagination;

            return View(result);
        }


        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Delete(int id)
        {
            _daoFactory.GymasiumDao().Delete(_daoFactory.GymasiumDao().Load(id));
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var gymasium = _daoFactory.GymasiumDao().Load(id);
            return View(new GymnasiumViewModel{Gymnasium=gymasium});
        }

        [HttpPost, Session]
        public ActionResult Save(GymnasiumViewModel model)
        {
            if (ModelState.IsValid)
            {
                _daoFactory.GymasiumDao().SaveOrUpdate(model.Gymnasium);
                return RedirectToAction("Index");
            }
            if (model.Gymnasium.Id != 0)
                return View("Edit", model);
            return View("Create", model);
        }
    }
}

src/Extends/Badminton/Badminton.Web.Plugin/Areas/Badminton/Controllers/MeasurementUnitController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using Badminton;
using Badminton.Dao;
using Qi.Web.Mvc;

namespace Badminton.Web.Plugin.Areas.Badminton.Controllers
{
    [Session, HandleError]
    public class MeasurementUnitController : Controller
    {
        private readonly IBadmintonDaoFactory _daoFactory;

        public MeasurementUnitController(IBadmintonDaoFactory daoFactory)
        {
            _daoFactory = daoFactory;
        }

        //
        // GET: /Badminton/MeasurementUnit/

        public ActionResult Index()
        {
            IList<MeasurementUnit> result = _daoFactory.MeasurementUnit().GetAll();
            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(MeasurementUnit unit)
        {
            if (this.ModelState.IsValid)
            {
                _daoFactory.MeasurementUnit().SaveOrUpdate(unit);
                return RedirectToAction("Index");
            }
            return View(unit.Id == 0 ? "Create" : "Edit", unit);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                throw new HttpException(404, "Can't find the MeasurementUnit");
            var result = _daoFactory.MeasurementUnit().Get(id.Value);
            return View(result);
        }
    }
}

src/Extends/Badminton/Badminton.Web.Plugin/Areas/Badminton/Controllers/ModelController.cs
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using Badminton.Consumableses;
using Badminton.Dao;
using Ornament.Web;
using Ornament.Web.UI.Paginations;
using Qi.Web.Mvc;

namespace Badminton.Web.Plugin.Areas.Badminton.Controllers
{
    [Session,]
    public class ModelController : Controller
    {
        private readonly IBadmintonDaoFactory _daoFactory;

        public ModelController(IBadmintonDaoFactory daoFactory)
        {
            _daoFactory = daoFactory;
        }

        //
        // GET: /Badminton/Model/

        public ActionResult Index(Pagination page)
        {
            IList<Model> list = _daoFactory.ModelDao().GetAll();
            page.TotalRows = list.Count;
            ViewData["nav"] = page;
            return View(list);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                throw new HttpException(404, "Not found Model ");
            }

            return View(_daoFactory.ModelDao().Get(id.Value));
        }

        [HttpPost]
        public ActionResult Save(Model model)
        {
            if (ModelState.IsValid)
            {
                _daoFactory.ModelDao().SaveOrUpdate(model);
                return Redirect("index");
            }
            return View(model.Id == 0 ? "Create" : "Edit", model);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
                throw new HttpException(404, "Not found Model ");
            Model model = _daoFactory.ModelDao().Get(id.Value);
            _daoFactory.ModelDao().Delete(model);
            return Json(new {success = true}, JsonRequestBehavior.AllowGet);
        }
    }
}

src/Extends/Badminton/Badminton.Web.Plugin/Areas/Badminton/Views/Brand/Create.cshtml
@using Ornament.Properties
@using Ornament
@model Badminton.Consumableses.Brand

@{
    ViewBag.Title = "Create";
    Layout = OrnamentContext.Configuration.Layout();
}
@section pageTitle{
    <h5>Creat3e Brand</h5>
}
@using (Html.BeginForm("Create", "Brand", FormMethod.Post))
{
    <div class="widget">
        @*<div class="navbar">
                <div class="navbar-inner">
                </div>
            </div>*@

        <div class="well form-horizontal">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.EditorFor(model => model.Name)
        </div>

        <div class="form-actions">
            <button class="btn btn-primary">@Resources.Create</button>
            <a href="@Url.Action("Index")" class="btn">@Resources.Cancel</a>
        </div>
    </div>

}


@*
    如果想定制新的js，请在创建下列路径，并且删除 @section Scripts的注释
    seajs.use必须是全小写
    please create a js in /Scripts/Module/Views/{Area}/{Controller}/Create.js
*@
@*

    @section Scripts {
        <script type="text/javascript">
            seajs.use(["{area}/{controller}/Create.js"],function(init){
                inti();
            });
        </script>
    }

*@

src/Extends/Badminton/Badminton.Web.Plugin/Areas/Badminton/Views/Brand/Edit.cshtml
@using Ornament.Properties
@using Ornament
@model Badminton.Consumableses.Brand

@{
    ViewBag.Title = "View1";
    Layout = OrnamentContext.Configuration.Layout();
}

<h2>View1</h2>

@using (Html.BeginForm())
{
    <div class="widget">
        <div class="navbar">
            <div class="navbar-inner">
                <button class="btn btn-primary">@Resources.Save</button>
                <a href="@Url.Action("Index")" class="btn">@Resources.Cancel</a>
            </div>
        </div>

        <div class="well form-horizontal">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.EditorFor(model => model.Name)
        </div>

        @Html.HiddenFor(model => model.Id)

        <div class="form-actions">
            <button class="btn btn-primary">@Resources.Save</button>
            <a href="@Url.Action("Index")" class="btn">@Resources.Cancel</a>
        </div>
    </div>
}


@*
    如果想定制新的js，请在创建下列路径，并且删除 @section Scripts的注释
    seajs.use必须是全小写
    please create a js in /Scripts/Module/Views/{Area}/{Controller}/View1.js
*@
@*

    @section Scripts {
        <script type="text/javascript">
            seajs.use(["{area}/{controller}/View1.js"],function(init){
                inti();
            });
        </script>
    }

*@

src/Extends/Badminton/Badminton.Web.Plugin/Areas/Badminton/Views/Brand/Index.cshtml
@model IEnumerable<Badminton.Consumableses.Brand>
@using Ornament;
@using Ornament.Properties
@{
    ViewBag.Title = "品牌";
    Layout = OrnamentContext.Configuration.Layout();
}

@section pageTitle
{
    <h6>品牌</h6>
}

<div class="widget">
    <div class="navbar">
        <div class="navbar-inner">
            <a id="add" class="btn btn-primary" href="#@Url.Action("Create")"><i class="icon-plus icon-white"></i>@Resources.Create</a>
        </div>
    </div>
    <div class="body well">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 100px"></th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(Resources.Edit, "Edit", new { id = item.Id }) |
                            @Html.ActionLink(Resources.Delete, "Delete", new { id = item.Id })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

src/Extends/Badminton/Badminton.Web.Plugin/Areas/Badminton/Views/Model/Create.cshtml
@using Ornament.Properties
@using Ornament
@model Badminton.Consumableses.Model

@{
    ViewBag.Title = "Create";
    Layout = OrnamentContext.Configuration.Layout();
}
@section pageTitle{
    <h5>Create</h5>
}

@using (Html.BeginForm("Save", "Model", FormMethod.Post))
{
    <div class="widget">
        <div class="navbar">
            <div class="navbar-inner">
                <button class="btn btn-primary">@Resources.Create</button>
                <a href="@Url.Action("Index")" class="btn">@Resources.Cancel</a>
            </div>
        </div>

        <div class="well form-horizontal">

            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.EditorFor(model => model.Prefix)
            @Html.EditorFor(model => model.Suffix)
            @Html.EditorFor(model => model.Name)
            @Html.EditorFor(model => model.Brand)
            @Html.EditorFor(model => model.ConsumablesType)
            <div class="form-actions">
                <button class="btn btn-primary">@Resources.Create</button>
                <a href="@Url.Action("Index")" class="btn">@Resources.Cancel</a>
            </div>
        </div>
    </div>

}


@*
    如果想定制新的js，请在创建下列路径，并且删除 @section Scripts的注释
    seajs.use必须是全小写
    please create a js in /Scripts/Module/Views/{Area}/{Controller}/Create.js
*@
@*

    @section Scripts {
        <script type="text/javascript">
            seajs.use(["{area}/{controller}/Create.js"],function(init){
                inti();
            });
        </script>
    }

*@

src/Extends/Badminton/Badminton.Web.Plugin/Areas/Badminton/Views/Model/Edit.cshtml
@using Ornament.Properties
@using Ornament
@model Badminton.Consumableses.Model

@{
    ViewBag.Title = "Edit";
    Layout = OrnamentContext.Configuration.Layout();
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    <div class="widget">
        <div class="navbar">
            <div class="navbar-inner">
                <button class="btn btn-primary">@Resources.Save</button>
                <a href="@Url.Action("Index")" class="btn">@Resources.Cancel</a>
            </div>
        </div>

        <div class="well form-horizontal">

            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)


            @Html.EditorFor(model => model.Prefix)


            @Html.EditorFor(model => model.Suffix)


            @Html.EditorFor(model => model.Name)

            @Html.HiddenFor(model => model.Id)

            <div class="form-actions">
                <button class="btn btn-primary">@Resources.Save</button>
                <a href="@Url.Action("Index")" class="btn">@Resources.Cancel</a>
            </div>
        </div>
        }


        @*
            如果想定制新的js，请在创建下列路径，并且删除 @section Scripts的注释
            seajs.use必须是全小写
            please create a js in /Scripts/Module/Views/{Area}/{Controller}/Edit.js
        *@
        @*

            @section Scripts {
                <script type="text/javascript">
                    seajs.use(["{area}/{controller}/Edit.js"],function(init){
                        inti();
                    });
                </script>
            }

        *@

src/Extends/Badminton/Badminton.Web.Plugin/Areas/Badminton/Views/Model/Index.cshtml
@using Ornament.Properties
@using Ornament.Web
@using Ornament
@model IEnumerable<Badminton.Consumableses.Model>

@{
    ViewBag.Title = "Model List";
    Layout = OrnamentContext.Configuration.Layout();
}
@section pageTitle{
    <h5>Model List</h5>
}


<div class="widget">
    <div class="navbar">
        <div class="navbar-inner">
            <a id="add" class="btn btn-primary" href="#@Url.Action("Create")"><i class="icon-plus icon-white"></i>@Resources.Resources.Create</a>
        </div>
    </div>
    <div class="body well">
        @if (Model.Count() != 0)
        {

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Prefix)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Suffix)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Prefix)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Suffix)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                <a href="#@Url.Action("Edit", new { id = item.Id })" title="@Resources.Edit" class="btn btn-info btn-mini"><i class="icon-edit icon-white"></i></a>
                                <a data-toggle="popover" data-val="@item.Id" class="btn btn-danger btn-small" href="#">@Resources.Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4">
                            <form>
                           
                            </form>
                        </td>
                    </tr>
                </tfoot>
            </table>
        }
        else
        {
            <div class="alert">
                <h6>
                    No Data Found.
                </h6>
            </div>
        }
    </div>
</div>
<div id="warning" class="hide">
    <p>Do you want to delete this model?</p>
    <p>
        <button class="btn btn-danger deleteYes">@Resources.Delete</button>
        <button class="btn deleteNo">@Resources.Cancel</button>
    </p>
</div>
@section scripts
{
    <script type="text/javascript">
        seajs.use("/badminton/model/index.js", function (main) {
            main("@Url.Action("Delete")");
        })
    </script>
}